version: 0.2
phases:
  pre_build:
    commands:
      - echo "Listing all extracted files to check for backslash filenames:"
      - ls -la
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 984312272694.dkr.ecr.eu-north-1.amazonaws.com
  build:
    commands:
      - docker build --no-cache -t whatsflow-backend .
  post_build:
    commands:
      - docker tag whatsflow-backend:latest 984312272694.dkr.ecr.eu-north-1.amazonaws.com/whatsflow-backend:latest
      - docker push 984312272694.dkr.ecr.eu-north-1.amazonaws.com/whatsflow-backend:latest
